### ISSUE TITLE
outdated packages

### ISSUE THREAD

**Issue by philshem** [tanrax/flask-contacts#8]
## Werkzeug 1.0 breaks Flask

+ Werkzeug's newest version is 1.0 and it's known to break Flask. For that reason, I'm adding `werkzeug==0.16` to the `requirements.txt` file. Read more: https://github.com/python-restx/flask-restx/issues/61#issuecomment-586644550

```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from forms import ContactForm
  File "/Users/XX/code/flask-contacts/forms.py", line 1, in <module>
    from flask_wtf import FlaskForm
  File "/Users/XX/code/flask-contacts/venv/lib/python3.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/Users/XX/code/flask-contacts/venv/lib/python3.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/Users/XX/code/flask-contacts/venv/lib/python3.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/Users/XX/code/flask-contacts/venv/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/Users/XX/code/flask-contacts/venv/lib/python3.7/site-packages/werkzeug/__init__.py)
```

## email_validator

+ Additionally, `email_validator` is required. Also added to `requirements.txt`

```
  File "app.py", line 3, in <module>
    from forms import ContactForm
  File "/Users/XX/code/flask-contacts/forms.py", line 6, in <module>
    class ContactForm(FlaskForm):
  File "/Users/XX/code/flask-contacts/forms.py", line 9, in ContactForm
    email = StringField('E-Mail', validators=[Email(), Length(min=-1, max=200, message='You cannot have more than 200 characters')])
  File "/Users/XX/code/flask-contacts/venv/lib/python3.7/site-packages/wtforms/validators.py", line 332, in __init__
    raise Exception("Install 'email_validator' for email validation support.")
```

**Comment by tanrax** [comment]
Thank you very much, several people will be grateful as me. 😄
